import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const InterFont= Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.className}`}>
        {children}
		  <Toaster/>
      </body>
    </html>
  );
}
